In [4]:
#Importing lib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
import joblib

In [5]:
# Reading Dataset
df=pd.read_csv('fake currency prediction.csv')
df

variance  skewness  curtosis  entropy  Target
0      3.62160   8.66610   -2.8073 -0.44699       0
1      4.54590   8.16740   -2.4586 -1.46210       0
2      3.86600  -2.63830    1.9242  0.10645       0
3      3.45660   9.52280   -4.0112 -3.59440       0
4      0.32924  -4.45520    4.5718 -0.98880       0
...        ...       ...       ...      ...     ...
1367   0.40614   1.34920   -1.4501 -0.55949       1
1368  -1.38870  -4.87730    6.4774  0.34179       1
1369  -3.75030 -13.45860   17.5932 -2.77710       1
1370  -3.56370  -8.38270   12.3930 -1.28230       1
1371  -2.54190  -0.65804    2.6842  1.19520       1

[1372 rows x 5 columns]

DATA PREPROCESSING

In [6]:
df.max()

variance     6.8248
skewness    12.9516
curtosis    17.9274
entropy      2.4495
Target       1.0000
dtype: float64

In [7]:
df.min()

variance    -7.0421
skewness   -13.7731
curtosis    -5.2861
entropy     -8.5482
Target       0.0000
dtype: float64

In [8]:
df.isna().sum()

variance    0
skewness    0
curtosis    0
entropy     0
Target      0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   Target    1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [10]:
df.describe()

variance     skewness     curtosis      entropy       Target
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [11]:
df['Target'].value_counts()

0    762
1    610
Name: Target, dtype: int64

In [12]:
y=df['Target']

In [13]:
x=df.drop("Target",axis=1)

Spliting of data into traing and tesing dataset

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler= StandardScaler()

In [16]:
x=scaler.fit_transform(x)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

 Building Random forest model

In [19]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000,criterion = "gini")

In [20]:
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=1000)

In [21]:
y_pred=rf.predict(x_test)

In [22]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score

accuracy_score(y_test,y_pred)

0.9927184466019418

In [23]:
confusion_matrix(y_test,y_pred,labels=[0,1])

array([[231,   3],
       [  0, 178]], dtype=int64)

In [24]:
precision_score(y_test, y_pred)

0.9834254143646409

In [25]:
x=[-0.48835287,  0.01023484, -0.86200821, -0.00192524]
y1=np.array([x])
y1.reshape(-1,1)
y1

array([[-0.48835287,  0.01023484, -0.86200821, -0.00192524]])

In [26]:
y2=rf.predict(y1)
print(y2)

[1]


In [27]:
x_test[1]

array([ 1.64954822,  1.13077407, -1.11161021, -0.16938171])

Dumping and loading the model

In [28]:
joblib.dump(rf,"randomforest_model")

['randomforest_model']

In [29]:
res=joblib.load("randomforest_model")

Testing the model

In [30]:
res.predict(x_test)

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,